In [1]:
import requests
from bs4 import BeautifulSoup

In [2]:
r = requests.get("https://en.wikipedia.org/wiki/List_of_countries_by_population_(United_Nations)")

In [3]:
soup = BeautifulSoup(r.text, "html.parser")

In [4]:
main_table = soup.find('table', id = 'main')

In [5]:
headers_footers = main_table.find_all('th')
headers = []
for header in headers_footers[0:6]:
    headers.append(header.text)
#     print(header.text)
#     print('\n')
headers

['Country or area\n',
 'UN continentalregion[4]\n',
 'UN statisticalregion[4]\n',
 'Population(1 July 2018)\n',
 'Population(1 July 2019)\n',
 'Change\n']

In [6]:
rows = main_table.find_all('tr')[1:]
master_list = []
for row in rows:
    country_list = []
    for i in row.find_all('td'):
        print(i.text)
        country_list.append(i.text)
    master_list.append(country_list)

 China[a]
Asia
Eastern Asia
1,427,647,786
1,433,783,686
+0.43%

 India
Asia
Southern Asia
1,352,642,280
1,366,417,754
+1.02%

 United States
Americas
Northern America
327,096,265
329,064,917
+0.60%

 Indonesia
Asia
South-eastern Asia
267,670,543
270,625,568
+1.10%

 Pakistan
Asia
Southern Asia
212,228,286
216,565,318
+2.04%

 Brazil
Americas
South America
209,469,323
211,049,527
+0.75%

 Nigeria
Africa
Western Africa
195,874,683
200,963,599
+2.60%

 Bangladesh
Asia
Southern Asia
161,376,708
163,046,161
+1.03%

 Russia
Europe
Eastern Europe
145,734,038
145,872,256
+0.09%

 Mexico
Americas
Central America
126,190,788
127,575,529
+1.10%

 Japan
Asia
Eastern Asia
127,202,192
126,860,301
−0.27%

 Ethiopia
Africa
Eastern Africa
109,224,414
112,078,730
+2.61%

 Philippines
Asia
South-eastern Asia
106,651,394
108,116,615
+1.37%

 Egypt
Africa
Northern Africa
98,423,598
100,388,073
+2.00%

 Vietnam
Asia
South-eastern Asia
95,545,962
96,462,106
+0.96%

 DR Congo
Africa
Middle Africa
84,068,091
86,790,567
+3.24%

 Germany
Europe
Western Europe
83,124,418
83,517,045
+0.47%

 Turkey
Asia
Western Asia
82,340,088
83,429,615
+1.32%

 Iran
Asia
Southern Asia
81,800,188
82,913,906
+1.36%

 Thailand
Asia
South-eastern Asia
68,863,514
69,037,513
+0.25%

 United Kingdom
Europe
Northern Europe
67,141,684
67,530,172
+0.58%

 France[b]
Europe
Western Europe
64,990,511
65,129,728
+0.21%

 Italy
Europe
Southern Europe
60,627,291
60,550,075
−0.13%

 South Africa
Africa
Southern Africa
57,792,518
58,558,270
+1.33%

 Tanzania[c]
Africa
Eastern Africa
56,313,438
58,005,463
+3.00%

 Myanmar
Asia
South-eastern Asia
53,708,320
54,045,420
+0.63%

 Kenya
Africa
Eastern Africa
51,392,565
52,573,973
+2.30%

 South Korea
Asia
Eastern Asia
51,171,706
51,225,308
+0.10%

 Colombia
Americas
South America
49,661,048
50,339,443
+1.37%

 Spain[d]
Europe
Southern Europe
46,692,858
46,736,776
+0.09%

 Argentina
Americas
South America
44,361,150
44,780,677
+0.95%

 Uganda
Africa
Eastern Africa
42,729,036
44,269,594
+3.61%

 Ukraine[e]
Europe
Eastern Europe
44,246,156
43,993,638
−0.57%

 Algeria
Africa
Northern Africa
42,228,408
43,053,054
+1.95%

 Sudan
Africa
Northern Africa
41,801,533
42,813,238
+2.42%

 Iraq
Asia
Western Asia
38,433,600
39,309,783
+2.28%

 Afghanistan
Asia
Southern Asia
37,171,921
38,041,754
+2.34%

 Poland
Europe
Eastern Europe
37,921,592
37,887,768
−0.09%

 Canada
Americas
Northern America
37,074,562
37,411,047
+0.91%

 Morocco
Africa
Northern Africa
36,029,093
36,471,769
+1.23%

 Saudi Arabia
Asia
Western Asia
33,702,756
34,268,528
+1.68%

 Uzbekistan
Asia
Central Asia
32,476,244
32,981,716
+1.56%

 Peru
Americas
South America
31,989,260
32,510,453
+1.63%

 Malaysia[f]
Asia
South-eastern Asia
31,528,033
31,949,777
+1.34%

 Angola
Africa
Middle Africa
30,809,787
31,825,295
+3.30%

 Mozambique
Africa
Eastern Africa
29,496,004
30,366,036
+2.95%

 Yemen
Asia
Western Asia
28,498,683
29,161,922
+2.33%

 Ghana
Africa
Western Africa
28,206,728
28,833,629
+2.22%

   Nepal
Asia
Southern Asia
28,095,714
28,608,710
+1.83%

 Venezuela
Americas
South America
28,887,118
28,515,829
−1.29%

 Madagascar
Africa
Eastern Africa
26,262,313
26,969,307
+2.69%

 North Korea
Asia
Eastern Asia
25,549,604
25,666,161
+0.46%

 Ivory Coast
Africa
Western Africa
25,069,230
25,716,544
+2.58%

 Cameroon
Africa
Middle Africa
25,216,267
25,876,380
+2.62%

 Australia[g]
Oceania
Australia and New Zealand
24,898,152
25,203,198
+1.23%

 Taiwan[h]
Asia
Eastern Asia
23,726,460
23,773,876
+0.20%

 Niger
Africa
Western Africa
22,442,822
23,310,715
+3.87%

 Sri Lanka
Asia
Southern Asia
21,228,763
21,323,733
+0.45%

 Burkina Faso
Africa
Western Africa
19,751,466
20,321,378
+2.89%

 Mali
Africa
Western Africa
19,077,749
19,658,031
+3.04%

 Romania
Europe
Eastern Europe
19,506,114
19,364,557
−0.73%

 Malawi
Africa
Eastern Africa
18,143,217
18,628,747
+2.68%

 Chile
Americas
South America
18,729,160
18,952,038
+1.19%

 Kazakhstan
Asia
Central Asia
18,319,618
18,551,427
+1.27%

 Zambia
Africa
Eastern Africa
17,351,708
17,861,030
+2.94%

 Guatemala
Americas
Central America
17,247,849
17,581,472
+1.93%

 Ecuador
Americas
South America
17,084,358
17,373,662
+1.69%

 Netherlands
Europe
Western Europe
17,059,560
17,097,130
+0.22%

 Syria
Asia
Western Asia
16,945,057
17,070,135
+0.74%

 Cambodia
Asia
South-eastern Asia
16,249,792
16,486,542
+1.46%

 Senegal
Africa
Western Africa
15,854,323
16,296,364
+2.79%

 Chad
Africa
Middle Africa
15,477,729
15,946,876
+3.03%

 Somalia
Africa
Eastern Africa
15,008,226
15,442,905
+2.90%

 Zimbabwe
Africa
Eastern Africa
14,438,802
14,645,468
+1.43%

 Guinea
Africa
Western Africa
12,414,293
12,771,246
+2.88%

 Rwanda
Africa
Eastern Africa
12,301,970
12,626,950
+2.64%

 Benin
Africa
Western Africa
11,485,044
11,801,151
+2.75%

 Tunisia
Africa
Northern Africa
11,565,201
11,694,719
+1.12%

 Belgium
Europe
Western Europe
11,482,178
11,539,328
+0.50%

 Bolivia
Americas
South America
11,353,142
11,513,100
+1.41%

 Cuba
Americas
Caribbean
11,338,134
11,333,483
−0.04%

 Haiti
Americas
Caribbean
11,123,178
11,263,770
+1.26%

 South Sudan
Africa
Eastern Africa
10,975,927
11,062,113
+0.79%

 Burundi
Africa
Eastern Africa
10,524,117
10,864,245
+3.23%

 Dominican Republic
Americas
Caribbean
10,627,141
10,738,958
+1.05%

 Czech Republic
Europe
Eastern Europe
10,665,677
10,689,209
+0.22%

 Greece
Europe
Southern Europe
10,522,246
10,473,455
−0.46%

 Portugal
Europe
Southern Europe
10,256,193
10,226,187
−0.29%

 Jordan
Asia
Western Asia
9,965,318
10,101,694
+1.37%

 Azerbaijan[i]
Asia
Western Asia
9,949,537
10,047,718
+0.99%

 Sweden
Europe
Northern Europe
9,971,638
10,036,379
+0.65%

 United Arab Emirates
Asia
Western Asia
9,630,959
9,770,529
+1.45%

 Honduras
Americas
Central America
9,587,522
9,746,117
+1.65%

 Hungary
Europe
Eastern Europe
9,707,499
9,684,679
−0.24%

 Belarus
Europe
Eastern Europe
9,452,617
9,452,411
0.00%

 Tajikistan
Asia
Central Asia
9,100,835
9,321,018
+2.42%

 Austria
Europe
Western Europe
8,891,388
8,955,102
+0.72%

 Papua New Guinea
Oceania
Melanesia
8,606,323
8,776,109
+1.97%

 Serbia[j]
Europe
Southern Europe
8,802,754
8,772,235
−0.35%

  Switzerland
Europe
Western Europe
8,525,611
8,591,365
+0.77%

 Israel
Asia
Western Asia
8,381,516
8,519,377
+1.64%

 Togo
Africa
Western Africa
7,889,093
8,082,366
+2.45%

 Sierra Leone
Africa
Western Africa
7,650,150
7,813,215
+2.13%

 Hong Kong
Asia
Eastern Asia
7,371,730
7,436,154
+0.87%

 Laos
Asia
South-eastern Asia
7,061,507
7,169,455
+1.53%

 Paraguay
Americas
South America
6,956,066
7,044,636
+1.27%

 Bulgaria
Europe
Eastern Europe
7,051,608
7,000,119
−0.73%

 Lebanon
Asia
Western Asia
6,859,408
6,855,713
−0.05%

 Libya
Africa
Northern Africa
6,678,559
6,777,452
+1.48%

 Nicaragua
Americas
Central America
6,465,501
6,545,502
+1.24%

 El Salvador
Americas
Central America
6,420,746
6,453,553
+0.51%

 Kyrgyzstan
Asia
Central Asia
6,304,030
6,415,850
+1.77%

 Turkmenistan
Asia
Central Asia
5,850,901
5,942,089
+1.56%

 Singapore
Asia
South-eastern Asia
5,757,499
5,804,337
+0.81%

 Denmark
Europe
Northern Europe
5,752,126
5,771,876
+0.34%

 Finland[k]
Europe
Northern Europe
5,522,576
5,532,156
+0.17%

 Slovakia
Europe
Eastern Europe
5,453,014
5,457,013
+0.07%

 Congo
Africa
Middle Africa
5,244,359
5,380,508
+2.60%

 Norway[l]
Europe
Northern Europe
5,337,962
5,378,857
+0.77%

 Costa Rica
Americas
Central America
4,999,441
5,047,561
+0.96%

 Palestine[m]
Asia
Western Asia
4,862,979
4,981,420
+2.44%

 Oman
Asia
Western Asia
4,829,473
4,974,986
+3.01%

 Liberia
Africa
Western Africa
4,818,973
4,937,374
+2.46%

 Ireland
Europe
Northern Europe
4,818,690
4,882,495
+1.32%

 New Zealand
Oceania
Australia and New Zealand
4,743,131
4,783,063
+0.84%

 Central African Republic
Africa
Middle Africa
4,666,368
4,745,185
+1.69%

 Mauritania
Africa
Western Africa
4,403,313
4,525,696
+2.78%

 Panama
Americas
Central America
4,176,869
4,246,439
+1.67%

 Kuwait
Asia
Western Asia
4,137,312
4,207,083
+1.69%

 Croatia
Europe
Southern Europe
4,156,405
4,130,304
−0.63%

 Moldova[n]
Europe
Eastern Europe
4,051,944
4,043,263
−0.21%

 Georgia[o]
Asia
Western Asia
4,002,942
3,996,765
−0.15%

 Eritrea
Africa
Eastern Africa
3,452,786
3,497,117
+1.28%

 Uruguay
Americas
South America
3,449,285
3,461,734
+0.36%

 Bosnia and Herzegovina
Europe
Southern Europe
3,323,925
3,301,000
−0.69%

 Mongolia
Asia
Eastern Asia
3,170,216
3,225,167
+1.73%

 Armenia
Asia
Western Asia
2,951,745
2,957,731
+0.20%

 Jamaica
Americas
Caribbean
2,934,847
2,948,279
+0.46%

 Puerto Rico
Americas
Caribbean
3,039,596
2,933,408
−3.49%

 Albania
Europe
Southern Europe
2,882,740
2,880,917
−0.06%

 Qatar
Asia
Western Asia
2,781,682
2,832,067
+1.81%

 Lithuania
Europe
Northern Europe
2,801,264
2,759,627
−1.49%

 Namibia
Africa
Southern Africa
2,448,301
2,494,530
+1.89%

 Gambia
Africa
Western Africa
2,280,094
2,347,706
+2.97%

 Botswana
Africa
Southern Africa
2,254,068
2,303,697
+2.20%

 Gabon
Africa
Middle Africa
2,119,275
2,172,579
+2.52%

 Lesotho
Africa
Southern Africa
2,108,328
2,125,268
+0.80%

 North Macedonia
Europe
Southern Europe
2,082,957
2,083,459
+0.02%

 Slovenia
Europe
Southern Europe
2,077,837
2,078,654
+0.04%

 Guinea-Bissau
Africa
Western Africa
1,874,303
1,920,922
+2.49%

 Latvia
Europe
Northern Europe
1,928,459
1,906,743
−1.13%

 Bahrain
Asia
Western Asia
1,569,446
1,641,172
+4.57%

 Trinidad and Tobago
Americas
Caribbean
1,389,843
1,394,973
+0.37%

 Equatorial Guinea
Africa
Middle Africa
1,308,975
1,355,986
+3.59%

 Estonia
Europe
Northern Europe
1,322,920
1,325,648
+0.21%

 East Timor
Asia
South-eastern Asia
1,267,974
1,293,119
+1.98%

 Mauritius[p]
Africa
Eastern Africa
1,189,265
1,198,575
+0.78%

 Cyprus[q]
Asia
Western Asia
1,170,125
1,179,551
+0.81%

 Eswatini
Africa
Southern Africa
1,136,281
1,148,130
+1.04%

 Djibouti
Africa
Eastern Africa
958,923
973,560
+1.53%

 Fiji
Oceania
Melanesia
883,483
889,953
+0.73%

 Réunion
Africa
Eastern Africa
882,526
888,927
+0.73%

 Comoros
Africa
Eastern Africa
832,322
850,886
+2.23%

 Guyana
Americas
South America
779,006
782,766
+0.48%

 Bhutan
Asia
Southern Asia
754,388
763,092
+1.15%

 Solomon Islands
Oceania
Melanesia
652,857
669,823
+2.60%

 Macau
Asia
Eastern Asia
631,636
640,445
+1.39%

 Montenegro
Europe
Southern Europe
627,809
627,987
+0.03%

 Luxembourg
Europe
Western Europe
604,245
615,729
+1.90%

 Western Sahara
Africa
Northern Africa
567,402
582,463
+2.65%

 Suriname
Americas
South America
575,990
581,372
+0.93%

 Cape Verde
Africa
Western Africa
543,767
549,935
+1.13%

 Maldives
Asia
Southern Asia
515,696
530,953
+2.96%

 Guadeloupe[r]
Americas
Caribbean
446,928
447,905
+0.22%

 Malta
Europe
Southern Europe
439,248
440,372
+0.26%

 Brunei
Asia
South-eastern Asia
428,963
433,285
+1.01%

 Belize
Americas
Central America
383,071
390,353
+1.90%

 Bahamas
Americas
Caribbean
385,637
389,482
+1.00%

 Martinique
Americas
Caribbean
375,673
375,554
−0.03%

 Iceland
Europe
Northern Europe
336,713
339,031
+0.69%

 Vanuatu
Oceania
Melanesia
292,680
299,882
+2.46%

 Barbados
Americas
Caribbean
286,641
287,025
+0.13%

 New Caledonia
Oceania
Melanesia
279,993
282,750
+0.98%

 French Guiana
Americas
South America
275,713
282,731
+2.55%

 French Polynesia
Oceania
Polynesia
277,679
279,287
+0.58%

 Mayotte
Africa
Eastern Africa
259,531
266,150
+2.55%

 São Tomé and Príncipe
Africa
Middle Africa
211,028
215,056
+1.91%

 Samoa
Oceania
Polynesia
196,129
197,097
+0.49%

 Saint Lucia
Americas
Caribbean
181,889
182,790
+0.50%

 Guernsey and  Jersey
Europe
Northern Europe
170,499
172,259
+1.03%

 Guam
Oceania
Micronesia
165,768
167,294
+0.92%

 Curaçao
Americas
Caribbean
162,752
163,424
+0.41%

 Kiribati
Oceania
Micronesia
115,847
117,606
+1.52%

 F.S. Micronesia
Oceania
Micronesia
112,640
113,815
+1.04%

 Grenada
Americas
Caribbean
111,454
112,003
+0.49%

 Tonga
Oceania
Polynesia
110,589
110,940
+0.32%

 Saint Vincent and the Grenadines
Americas
Caribbean
110,211
110,589
+0.34%

 Aruba
Americas
Caribbean
105,845
106,314
+0.44%

 U.S. Virgin Islands
Americas
Caribbean
104,680
104,578
−0.10%

 Seychelles
Africa
Eastern Africa
97,096
97,739
+0.66%

 Antigua and Barbuda
Americas
Caribbean
96,286
97,118
+0.86%

 Isle of Man
Europe
Northern Europe
84,077
84,584
+0.60%

 Andorra
Europe
Southern Europe
77,006
77,142
+0.18%

 Dominica
Americas
Caribbean
71,625
71,808
+0.26%

 Cayman Islands
Americas
Caribbean
64,174
64,948
+1.21%

 Bermuda
Americas
Northern America
62,756
62,506
−0.40%

 Marshall Islands
Oceania
Micronesia
58,413
58,791
+0.65%

 Greenland
Americas
Northern America
56,564
56,672
+0.19%

 Northern Mariana Islands
Oceania
Micronesia
56,882
56,188
−1.22%

 American Samoa
Oceania
Polynesia
55,465
55,312
−0.28%

 Saint Kitts and Nevis
Americas
Caribbean
52,441
52,823
+0.73%

 Faroe Islands
Europe
Northern Europe
48,497
48,678
+0.37%

 Sint Maarten
Americas
Caribbean
41,940
42,388
+1.07%

 Monaco
Europe
Western Europe
38,682
38,964
+0.73%

 Turks and Caicos Islands
Americas
Caribbean
37,665
38,191
+1.40%

 Liechtenstein
Europe
Western Europe
37,910
38,019
+0.29%

 San Marino
Europe
Southern Europe
33,785
33,860
+0.22%

 Gibraltar
Europe
Southern Europe
33,718
33,701
−0.05%

 British Virgin Islands
Americas
Caribbean
29,802
30,030
+0.77%

 Caribbean Netherlands[s]
Americas
Caribbean
25,711
25,979
+1.04%

 Palau
Oceania
Micronesia
17,907
18,008
+0.56%

 Cook Islands
Oceania
Polynesia
17,518
17,548
+0.17%

 Anguilla
Americas
Caribbean
14,731
14,869
+0.94%

 Tuvalu
Oceania
Polynesia
11,508
11,646
+1.20%

 Wallis and Futuna
Oceania
Polynesia
11,661
11,432
−1.96%

 Nauru
Oceania
Micronesia
10,670
10,756
+0.81%

 Saint Helena, Ascension and Tristan da Cunha
Africa
Western Africa
6,035
6,059
+0.40%

 Saint Pierre and Miquelon
Americas
Northern America
5,849
5,822
−0.46%

 Montserrat
Americas
Caribbean
4,993
4,989
−0.08%

 Falkland Islands
Americas
South America
3,234
3,377
+4.42%

 Niue
Oceania
Polynesia
1,620
1,615
−0.31%

 Tokelau
Oceania
Polynesia
1,319
1,340
+1.59%

  Vatican City[t]
Europe
Southern Europe
801
799
−0.25%

In [7]:
headers

['Country or area\n',
 'UN continentalregion[4]\n',
 'UN statisticalregion[4]\n',
 'Population(1 July 2018)\n',
 'Population(1 July 2019)\n',
 'Change\n']

In [8]:
master_list

[['\xa0China[a]',
  'Asia',
  'Eastern Asia',
  '1,427,647,786',
  '1,433,783,686',
  '+0.43%\n'],
 ['\xa0India',
  'Asia',
  'Southern Asia',
  '1,352,642,280',
  '1,366,417,754',
  '+1.02%\n'],
 ['\xa0United States',
  'Americas',
  'Northern America',
  '327,096,265',
  '329,064,917',
  '+0.60%\n'],
 ['\xa0Indonesia',
  'Asia',
  'South-eastern Asia',
  '267,670,543',
  '270,625,568',
  '+1.10%\n'],
 ['\xa0Pakistan',
  'Asia',
  'Southern Asia',
  '212,228,286',
  '216,565,318',
  '+2.04%\n'],
 ['\xa0Brazil',
  'Americas',
  'South America',
  '209,469,323',
  '211,049,527',
  '+0.75%\n'],
 ['\xa0Nigeria',
  'Africa',
  'Western Africa',
  '195,874,683',
  '200,963,599',
  '+2.60%\n'],
 ['\xa0Bangladesh',
  'Asia',
  'Southern Asia',
  '161,376,708',
  '163,046,161',
  '+1.03%\n'],
 ['\xa0Russia',
  'Europe',
  'Eastern Europe',
  '145,734,038',
  '145,872,256',
  '+0.09%\n'],
 ['\xa0Mexico',
  'Americas',
  'Central America',
  '126,190,788',
  '127,575,529',
  '+1.10%\n'],
 ['\xa0Japan',
  'Asia',
  'Eastern Asia',
  '127,202,192',
  '126,860,301',
  '−0.27%\n'],
 ['\xa0Ethiopia',
  'Africa',
  'Eastern Africa',
  '109,224,414',
  '112,078,730',
  '+2.61%\n'],
 ['\xa0Philippines',
  'Asia',
  'South-eastern Asia',
  '106,651,394',
  '108,116,615',
  '+1.37%\n'],
 ['\xa0Egypt',
  'Africa',
  'Northern Africa',
  '98,423,598',
  '100,388,073',
  '+2.00%\n'],
 ['\xa0Vietnam',
  'Asia',
  'South-eastern Asia',
  '95,545,962',
  '96,462,106',
  '+0.96%\n'],
 ['\xa0DR Congo',
  'Africa',
  'Middle Africa',
  '84,068,091',
  '86,790,567',
  '+3.24%\n'],
 ['\xa0Germany',
  'Europe',
  'Western Europe',
  '83,124,418',
  '83,517,045',
  '+0.47%\n'],
 ['\xa0Turkey',
  'Asia',
  'Western Asia',
  '82,340,088',
  '83,429,615',
  '+1.32%\n'],
 ['\xa0Iran', 'Asia', 'Southern Asia', '81,800,188', '82,913,906', '+1.36%\n'],
 ['\xa0Thailand',
  'Asia',
  'South-eastern Asia',
  '68,863,514',
  '69,037,513',
  '+0.25%\n'],
 ['\xa0United Kingdom',
  'Europe',
  'Northern Europe',
  '67,141,684',
  '67,530,172',
  '+0.58%\n'],
 ['\xa0France[b]',
  'Europe',
  'Western Europe',
  '64,990,511',
  '65,129,728',
  '+0.21%\n'],
 ['\xa0Italy',
  'Europe',
  'Southern Europe',
  '60,627,291',
  '60,550,075',
  '−0.13%\n'],
 ['\xa0South Africa',
  'Africa',
  'Southern Africa',
  '57,792,518',
  '58,558,270',
  '+1.33%\n'],
 ['\xa0Tanzania[c]',
  'Africa',
  'Eastern Africa',
  '56,313,438',
  '58,005,463',
  '+3.00%\n'],
 ['\xa0Myanmar',
  'Asia',
  'South-eastern Asia',
  '53,708,320',
  '54,045,420',
  '+0.63%\n'],
 ['\xa0Kenya',
  'Africa',
  'Eastern Africa',
  '51,392,565',
  '52,573,973',
  '+2.30%\n'],
 ['\xa0South Korea',
  'Asia',
  'Eastern Asia',
  '51,171,706',
  '51,225,308',
  '+0.10%\n'],
 ['\xa0Colombia',
  'Americas',
  'South America',
  '49,661,048',
  '50,339,443',
  '+1.37%\n'],
 ['\xa0Spain[d]',
  'Europe',
  'Southern Europe',
  '46,692,858',
  '46,736,776',
  '+0.09%\n'],
 ['\xa0Argentina',
  'Americas',
  'South America',
  '44,361,150',
  '44,780,677',
  '+0.95%\n'],
 ['\xa0Uganda',
  'Africa',
  'Eastern Africa',
  '42,729,036',
  '44,269,594',
  '+3.61%\n'],
 ['\xa0Ukraine[e]',
  'Europe',
  'Eastern Europe',
  '44,246,156',
  '43,993,638',
  '−0.57%\n'],
 ['\xa0Algeria',
  'Africa',
  'Northern Africa',
  '42,228,408',
  '43,053,054',
  '+1.95%\n'],
 ['\xa0Sudan',
  'Africa',
  'Northern Africa',
  '41,801,533',
  '42,813,238',
  '+2.42%\n'],
 ['\xa0Iraq', 'Asia', 'Western Asia', '38,433,600', '39,309,783', '+2.28%\n'],
 ['\xa0Afghanistan',
  'Asia',
  'Southern Asia',
  '37,171,921',
  '38,041,754',
  '+2.34%\n'],
 ['\xa0Poland',
  'Europe',
  'Eastern Europe',
  '37,921,592',
  '37,887,768',
  '−0.09%\n'],
 ['\xa0Canada',
  'Americas',
  'Northern America',
  '37,074,562',
  '37,411,047',
  '+0.91%\n'],
 ['\xa0Morocco',
  'Africa',
  'Northern Africa',
  '36,029,093',
  '36,471,769',
  '+1.23%\n'],
 ['\xa0Saudi Arabia',
  'Asia',
  'Western Asia',
  '33,702,756',
  '34,268,528',
  '+1.68%\n'],
 ['\xa0Uzbekistan',
  'Asia',
  'Central Asia',
  '32,476,244',
  '32,981,716',
  '+1.56%\n'],
 ['\xa0Peru',
  'Americas',
  'South America',
  '31,989,260',
  '32,510,453',
  '+1.63%\n'],
 ['\xa0Malaysia[f]',
  'Asia',
  'South-eastern Asia',
  '31,528,033',
  '31,949,777',
  '+1.34%\n'],
 ['\xa0Angola',
  'Africa',
  'Middle Africa',
  '30,809,787',
  '31,825,295',
  '+3.30%\n'],
 ['\xa0Mozambique',
  'Africa',
  'Eastern Africa',
  '29,496,004',
  '30,366,036',
  '+2.95%\n'],
 ['\xa0Yemen', 'Asia', 'Western Asia', '28,498,683', '29,161,922', '+2.33%\n'],
 ['\xa0Ghana',
  'Africa',
  'Western Africa',
  '28,206,728',
  '28,833,629',
  '+2.22%\n'],
 ['\xa0\xa0\xa0Nepal',
  'Asia',
  'Southern Asia',
  '28,095,714',
  '28,608,710',
  '+1.83%\n'],
 ['\xa0Venezuela',
  'Americas',
  'South America',
  '28,887,118',
  '28,515,829',
  '−1.29%\n'],
 ['\xa0Madagascar',
  'Africa',
  'Eastern Africa',
  '26,262,313',
  '26,969,307',
  '+2.69%\n'],
 ['\xa0North Korea',
  'Asia',
  'Eastern Asia',
  '25,549,604',
  '25,666,161',
  '+0.46%\n'],
 ['\xa0Ivory Coast',
  'Africa',
  'Western Africa',
  '25,069,230',
  '25,716,544',
  '+2.58%\n'],
 ['\xa0Cameroon',
  'Africa',
  'Middle Africa',
  '25,216,267',
  '25,876,380',
  '+2.62%\n'],
 ['\xa0Australia[g]',
  'Oceania',
  'Australia and New Zealand',
  '24,898,152',
  '25,203,198',
  '+1.23%\n'],
 ['\xa0Taiwan[h]',
  'Asia',
  'Eastern Asia',
  '23,726,460',
  '23,773,876',
  '+0.20%\n'],
 ['\xa0Niger',
  'Africa',
  'Western Africa',
  '22,442,822',
  '23,310,715',
  '+3.87%\n'],
 ['\xa0Sri Lanka',
  'Asia',
  'Southern Asia',
  '21,228,763',
  '21,323,733',
  '+0.45%\n'],
 ['\xa0Burkina Faso',
  'Africa',
  'Western Africa',
  '19,751,466',
  '20,321,378',
  '+2.89%\n'],
 ['\xa0Mali',
  'Africa',
  'Western Africa',
  '19,077,749',
  '19,658,031',
  '+3.04%\n'],
 ['\xa0Romania',
  'Europe',
  'Eastern Europe',
  '19,506,114',
  '19,364,557',
  '−0.73%\n'],
 ['\xa0Malawi',
  'Africa',
  'Eastern Africa',
  '18,143,217',
  '18,628,747',
  '+2.68%\n'],
 ['\xa0Chile',
  'Americas',
  'South America',
  '18,729,160',
  '18,952,038',
  '+1.19%\n'],
 ['\xa0Kazakhstan',
  'Asia',
  'Central Asia',
  '18,319,618',
  '18,551,427',
  '+1.27%\n'],
 ['\xa0Zambia',
  'Africa',
  'Eastern Africa',
  '17,351,708',
  '17,861,030',
  '+2.94%\n'],
 ['\xa0Guatemala',
  'Americas',
  'Central America',
  '17,247,849',
  '17,581,472',
  '+1.93%\n'],
 ['\xa0Ecuador',
  'Americas',
  'South America',
  '17,084,358',
  '17,373,662',
  '+1.69%\n'],
 ['\xa0Netherlands',
  'Europe',
  'Western Europe',
  '17,059,560',
  '17,097,130',
  '+0.22%\n'],
 ['\xa0Syria', 'Asia', 'Western Asia', '16,945,057', '17,070,135', '+0.74%\n'],
 ['\xa0Cambodia',
  'Asia',
  'South-eastern Asia',
  '16,249,792',
  '16,486,542',
  '+1.46%\n'],
 ['\xa0Senegal',
  'Africa',
  'Western Africa',
  '15,854,323',
  '16,296,364',
  '+2.79%\n'],
 ['\xa0Chad',
  'Africa',
  'Middle Africa',
  '15,477,729',
  '15,946,876',
  '+3.03%\n'],
 ['\xa0Somalia',
  'Africa',
  'Eastern Africa',
  '15,008,226',
  '15,442,905',
  '+2.90%\n'],
 ['\xa0Zimbabwe',
  'Africa',
  'Eastern Africa',
  '14,438,802',
  '14,645,468',
  '+1.43%\n'],
 ['\xa0Guinea',
  'Africa',
  'Western Africa',
  '12,414,293',
  '12,771,246',
  '+2.88%\n'],
 ['\xa0Rwanda',
  'Africa',
  'Eastern Africa',
  '12,301,970',
  '12,626,950',
  '+2.64%\n'],
 ['\xa0Benin',
  'Africa',
  'Western Africa',
  '11,485,044',
  '11,801,151',
  '+2.75%\n'],
 ['\xa0Tunisia',
  'Africa',
  'Northern Africa',
  '11,565,201',
  '11,694,719',
  '+1.12%\n'],
 ['\xa0Belgium',
  'Europe',
  'Western Europe',
  '11,482,178',
  '11,539,328',
  '+0.50%\n'],
 ['\xa0Bolivia',
  'Americas',
  'South America',
  '11,353,142',
  '11,513,100',
  '+1.41%\n'],
 ['\xa0Cuba', 'Americas', 'Caribbean', '11,338,134', '11,333,483', '−0.04%\n'],
 ['\xa0Haiti',
  'Americas',
  'Caribbean',
  '11,123,178',
  '11,263,770',
  '+1.26%\n'],
 ['\xa0South Sudan',
  'Africa',
  'Eastern Africa',
  '10,975,927',
  '11,062,113',
  '+0.79%\n'],
 ['\xa0Burundi',
  'Africa',
  'Eastern Africa',
  '10,524,117',
  '10,864,245',
  '+3.23%\n'],
 ['\xa0Dominican Republic',
  'Americas',
  'Caribbean',
  '10,627,141',
  '10,738,958',
  '+1.05%\n'],
 ['\xa0Czech Republic',
  'Europe',
  'Eastern Europe',
  '10,665,677',
  '10,689,209',
  '+0.22%\n'],
 ['\xa0Greece',
  'Europe',
  'Southern Europe',
  '10,522,246',
  '10,473,455',
  '−0.46%\n'],
 ['\xa0Portugal',
  'Europe',
  'Southern Europe',
  '10,256,193',
  '10,226,187',
  '−0.29%\n'],
 ['\xa0Jordan', 'Asia', 'Western Asia', '9,965,318', '10,101,694', '+1.37%\n'],
 ['\xa0Azerbaijan[i]',
  'Asia',
  'Western Asia',
  '9,949,537',
  '10,047,718',
  '+0.99%\n'],
 ['\xa0Sweden',
  'Europe',
  'Northern Europe',
  '9,971,638',
  '10,036,379',
  '+0.65%\n'],
 ['\xa0United Arab Emirates',
  'Asia',
  'Western Asia',
  '9,630,959',
  '9,770,529',
  '+1.45%\n'],
 ['\xa0Honduras',
  'Americas',
  'Central America',
  '9,587,522',
  '9,746,117',
  '+1.65%\n'],
 ['\xa0Hungary',
  'Europe',
  'Eastern Europe',
  '9,707,499',
  '9,684,679',
  '−0.24%\n'],
 ['\xa0Belarus',
  'Europe',
  'Eastern Europe',
  '9,452,617',
  '9,452,411',
  '0.00%\n'],
 ['\xa0Tajikistan',
  'Asia',
  'Central Asia',
  '9,100,835',
  '9,321,018',
  '+2.42%\n'],
 ['\xa0Austria',
  'Europe',
  'Western Europe',
  '8,891,388',
  '8,955,102',
  '+0.72%\n'],
 ['\xa0Papua New Guinea',
  'Oceania',
  'Melanesia',
  '8,606,323',
  '8,776,109',
  '+1.97%\n'],
 ['\xa0Serbia[j]',
  'Europe',
  'Southern Europe',
  '8,802,754',
  '8,772,235',
  '−0.35%\n'],
 ['\xa0\xa0Switzerland',
  'Europe',
  'Western Europe',
  '8,525,611',
  '8,591,365',
  '+0.77%\n'],
 ['\xa0Israel', 'Asia', 'Western Asia', '8,381,516', '8,519,377', '+1.64%\n'],
 ['\xa0Togo',
  'Africa',
  'Western Africa',
  '7,889,093',
  '8,082,366',
  '+2.45%\n'],
 ['\xa0Sierra Leone',
  'Africa',
  'Western Africa',
  '7,650,150',
  '7,813,215',
  '+2.13%\n'],
 ['\xa0Hong Kong',
  'Asia',
  'Eastern Asia',
  '7,371,730',
  '7,436,154',
  '+0.87%\n'],
 ['\xa0Laos',
  'Asia',
  'South-eastern Asia',
  '7,061,507',
  '7,169,455',
  '+1.53%\n'],
 ['\xa0Paraguay',
  'Americas',
  'South America',
  '6,956,066',
  '7,044,636',
  '+1.27%\n'],
 ['\xa0Bulgaria',
  'Europe',
  'Eastern Europe',
  '7,051,608',
  '7,000,119',
  '−0.73%\n'],
 ['\xa0Lebanon', 'Asia', 'Western Asia', '6,859,408', '6,855,713', '−0.05%\n'],
 ['\xa0Libya',
  'Africa',
  'Northern Africa',
  '6,678,559',
  '6,777,452',
  '+1.48%\n'],
 ['\xa0Nicaragua',
  'Americas',
  'Central America',
  '6,465,501',
  '6,545,502',
  '+1.24%\n'],
 ['\xa0El Salvador',
  'Americas',
  'Central America',
  '6,420,746',
  '6,453,553',
  '+0.51%\n'],
 ['\xa0Kyrgyzstan',
  'Asia',
  'Central Asia',
  '6,304,030',
  '6,415,850',
  '+1.77%\n'],
 ['\xa0Turkmenistan',
  'Asia',
  'Central Asia',
  '5,850,901',
  '5,942,089',
  '+1.56%\n'],
 ['\xa0Singapore',
  'Asia',
  'South-eastern Asia',
  '5,757,499',
  '5,804,337',
  '+0.81%\n'],
 ['\xa0Denmark',
  'Europe',
  'Northern Europe',
  '5,752,126',
  '5,771,876',
  '+0.34%\n'],
 ['\xa0Finland[k]',
  'Europe',
  'Northern Europe',
  '5,522,576',
  '5,532,156',
  '+0.17%\n'],
 ['\xa0Slovakia',
  'Europe',
  'Eastern Europe',
  '5,453,014',
  '5,457,013',
  '+0.07%\n'],
 ['\xa0Congo',
  'Africa',
  'Middle Africa',
  '5,244,359',
  '5,380,508',
  '+2.60%\n'],
 ['\xa0Norway[l]',
  'Europe',
  'Northern Europe',
  '5,337,962',
  '5,378,857',
  '+0.77%\n'],
 ['\xa0Costa Rica',
  'Americas',
  'Central America',
  '4,999,441',
  '5,047,561',
  '+0.96%\n'],
 ['\xa0Palestine[m]',
  'Asia',
  'Western Asia',
  '4,862,979',
  '4,981,420',
  '+2.44%\n'],
 ['\xa0Oman', 'Asia', 'Western Asia', '4,829,473', '4,974,986', '+3.01%\n'],
 ['\xa0Liberia',
  'Africa',
  'Western Africa',
  '4,818,973',
  '4,937,374',
  '+2.46%\n'],
 ['\xa0Ireland',
  'Europe',
  'Northern Europe',
  '4,818,690',
  '4,882,495',
  '+1.32%\n'],
 ['\xa0New Zealand',
  'Oceania',
  'Australia and New Zealand',
  '4,743,131',
  '4,783,063',
  '+0.84%\n'],
 ['\xa0Central African Republic',
  'Africa',
  'Middle Africa',
  '4,666,368',
  '4,745,185',
  '+1.69%\n'],
 ['\xa0Mauritania',
  'Africa',
  'Western Africa',
  '4,403,313',
  '4,525,696',
  '+2.78%\n'],
 ['\xa0Panama',
  'Americas',
  'Central America',
  '4,176,869',
  '4,246,439',
  '+1.67%\n'],
 ['\xa0Kuwait', 'Asia', 'Western Asia', '4,137,312', '4,207,083', '+1.69%\n'],
 ['\xa0Croatia',
  'Europe',
  'Southern Europe',
  '4,156,405',
  '4,130,304',
  '−0.63%\n'],
 ['\xa0Moldova[n]',
  'Europe',
  'Eastern Europe',
  '4,051,944',
  '4,043,263',
  '−0.21%\n'],
 ['\xa0Georgia[o]',
  'Asia',
  'Western Asia',
  '4,002,942',
  '3,996,765',
  '−0.15%\n'],
 ['\xa0Eritrea',
  'Africa',
  'Eastern Africa',
  '3,452,786',
  '3,497,117',
  '+1.28%\n'],
 ['\xa0Uruguay',
  'Americas',
  'South America',
  '3,449,285',
  '3,461,734',
  '+0.36%\n'],
 ['\xa0Bosnia and Herzegovina',
  'Europe',
  'Southern Europe',
  '3,323,925',
  '3,301,000',
  '−0.69%\n'],
 ['\xa0Mongolia',
  'Asia',
  'Eastern Asia',
  '3,170,216',
  '3,225,167',
  '+1.73%\n'],
 ['\xa0Armenia', 'Asia', 'Western Asia', '2,951,745', '2,957,731', '+0.20%\n'],
 ['\xa0Jamaica',
  'Americas',
  'Caribbean',
  '2,934,847',
  '2,948,279',
  '+0.46%\n'],
 ['\xa0Puerto Rico',
  'Americas',
  'Caribbean',
  '3,039,596',
  '2,933,408',
  '−3.49%\n'],
 ['\xa0Albania',
  'Europe',
  'Southern Europe',
  '2,882,740',
  '2,880,917',
  '−0.06%\n'],
 ['\xa0Qatar', 'Asia', 'Western Asia', '2,781,682', '2,832,067', '+1.81%\n'],
 ['\xa0Lithuania',
  'Europe',
  'Northern Europe',
  '2,801,264',
  '2,759,627',
  '−1.49%\n'],
 ['\xa0Namibia',
  'Africa',
  'Southern Africa',
  '2,448,301',
  '2,494,530',
  '+1.89%\n'],
 ['\xa0Gambia',
  'Africa',
  'Western Africa',
  '2,280,094',
  '2,347,706',
  '+2.97%\n'],
 ['\xa0Botswana',
  'Africa',
  'Southern Africa',
  '2,254,068',
  '2,303,697',
  '+2.20%\n'],
 ['\xa0Gabon',
  'Africa',
  'Middle Africa',
  '2,119,275',
  '2,172,579',
  '+2.52%\n'],
 ['\xa0Lesotho',
  'Africa',
  'Southern Africa',
  '2,108,328',
  '2,125,268',
  '+0.80%\n'],
 ['\xa0North Macedonia',
  'Europe',
  'Southern Europe',
  '2,082,957',
  '2,083,459',
  '+0.02%\n'],
 ['\xa0Slovenia',
  'Europe',
  'Southern Europe',
  '2,077,837',
  '2,078,654',
  '+0.04%\n'],
 ['\xa0Guinea-Bissau',
  'Africa',
  'Western Africa',
  '1,874,303',
  '1,920,922',
  '+2.49%\n'],
 ['\xa0Latvia',
  'Europe',
  'Northern Europe',
  '1,928,459',
  '1,906,743',
  '−1.13%\n'],
 ['\xa0Bahrain', 'Asia', 'Western Asia', '1,569,446', '1,641,172', '+4.57%\n'],
 ['\xa0Trinidad and Tobago',
  'Americas',
  'Caribbean',
  '1,389,843',
  '1,394,973',
  '+0.37%\n'],
 ['\xa0Equatorial Guinea',
  'Africa',
  'Middle Africa',
  '1,308,975',
  '1,355,986',
  '+3.59%\n'],
 ['\xa0Estonia',
  'Europe',
  'Northern Europe',
  '1,322,920',
  '1,325,648',
  '+0.21%\n'],
 ['\xa0East Timor',
  'Asia',
  'South-eastern Asia',
  '1,267,974',
  '1,293,119',
  '+1.98%\n'],
 ['\xa0Mauritius[p]',
  'Africa',
  'Eastern Africa',
  '1,189,265',
  '1,198,575',
  '+0.78%\n'],
 ['\xa0Cyprus[q]',
  'Asia',
  'Western Asia',
  '1,170,125',
  '1,179,551',
  '+0.81%\n'],
 ['\xa0Eswatini',
  'Africa',
  'Southern Africa',
  '1,136,281',
  '1,148,130',
  '+1.04%\n'],
 ['\xa0Djibouti',
  'Africa',
  'Eastern Africa',
  '958,923',
  '973,560',
  '+1.53%\n'],
 ['\xa0Fiji', 'Oceania', 'Melanesia', '883,483', '889,953', '+0.73%\n'],
 ['\xa0Réunion', 'Africa', 'Eastern Africa', '882,526', '888,927', '+0.73%\n'],
 ['\xa0Comoros', 'Africa', 'Eastern Africa', '832,322', '850,886', '+2.23%\n'],
 ['\xa0Guyana', 'Americas', 'South America', '779,006', '782,766', '+0.48%\n'],
 ['\xa0Bhutan', 'Asia', 'Southern Asia', '754,388', '763,092', '+1.15%\n'],
 ['\xa0Solomon Islands',
  'Oceania',
  'Melanesia',
  '652,857',
  '669,823',
  '+2.60%\n'],
 ['\xa0Macau', 'Asia', 'Eastern Asia', '631,636', '640,445', '+1.39%\n'],
 ['\xa0Montenegro',
  'Europe',
  'Southern Europe',
  '627,809',
  '627,987',
  '+0.03%\n'],
 ['\xa0Luxembourg',
  'Europe',
  'Western Europe',
  '604,245',
  '615,729',
  '+1.90%\n'],
 ['\xa0Western Sahara',
  'Africa',
  'Northern Africa',
  '567,402',
  '582,463',
  '+2.65%\n'],
 ['\xa0Suriname',
  'Americas',
  'South America',
  '575,990',
  '581,372',
  '+0.93%\n'],
 ['\xa0Cape Verde',
  'Africa',
  'Western Africa',
  '543,767',
  '549,935',
  '+1.13%\n'],
 ['\xa0Maldives', 'Asia', 'Southern Asia', '515,696', '530,953', '+2.96%\n'],
 ['\xa0Guadeloupe[r]',
  'Americas',
  'Caribbean',
  '446,928',
  '447,905',
  '+0.22%\n'],
 ['\xa0Malta', 'Europe', 'Southern Europe', '439,248', '440,372', '+0.26%\n'],
 ['\xa0Brunei',
  'Asia',
  'South-eastern Asia',
  '428,963',
  '433,285',
  '+1.01%\n'],
 ['\xa0Belize',
  'Americas',
  'Central America',
  '383,071',
  '390,353',
  '+1.90%\n'],
 ['\xa0Bahamas', 'Americas', 'Caribbean', '385,637', '389,482', '+1.00%\n'],
 ['\xa0Martinique', 'Americas', 'Caribbean', '375,673', '375,554', '−0.03%\n'],
 ['\xa0Iceland',
  'Europe',
  'Northern Europe',
  '336,713',
  '339,031',
  '+0.69%\n'],
 ['\xa0Vanuatu', 'Oceania', 'Melanesia', '292,680', '299,882', '+2.46%\n'],
 ['\xa0Barbados', 'Americas', 'Caribbean', '286,641', '287,025', '+0.13%\n'],
 ['\xa0New Caledonia',
  'Oceania',
  'Melanesia',
  '279,993',
  '282,750',
  '+0.98%\n'],
 ['\xa0French Guiana',
  'Americas',
  'South America',
  '275,713',
  '282,731',
  '+2.55%\n'],
 ['\xa0French Polynesia',
  'Oceania',
  'Polynesia',
  '277,679',
  '279,287',
  '+0.58%\n'],
 ['\xa0Mayotte', 'Africa', 'Eastern Africa', '259,531', '266,150', '+2.55%\n'],
 ['\xa0São Tomé and Príncipe',
  'Africa',
  'Middle Africa',
  '211,028',
  '215,056',
  '+1.91%\n'],
 ['\xa0Samoa', 'Oceania', 'Polynesia', '196,129', '197,097', '+0.49%\n'],
 ['\xa0Saint Lucia',
  'Americas',
  'Caribbean',
  '181,889',
  '182,790',
  '+0.50%\n'],
 ['\xa0Guernsey and \xa0Jersey',
  'Europe',
  'Northern Europe',
  '170,499',
  '172,259',
  '+1.03%\n'],
 ['\xa0Guam', 'Oceania', 'Micronesia', '165,768', '167,294', '+0.92%\n'],
 ['\xa0Curaçao', 'Americas', 'Caribbean', '162,752', '163,424', '+0.41%\n'],
 ['\xa0Kiribati', 'Oceania', 'Micronesia', '115,847', '117,606', '+1.52%\n'],
 ['\xa0F.S. Micronesia',
  'Oceania',
  'Micronesia',
  '112,640',
  '113,815',
  '+1.04%\n'],
 ['\xa0Grenada', 'Americas', 'Caribbean', '111,454', '112,003', '+0.49%\n'],
 ['\xa0Tonga', 'Oceania', 'Polynesia', '110,589', '110,940', '+0.32%\n'],
 ['\xa0Saint Vincent and the Grenadines',
  'Americas',
  'Caribbean',
  '110,211',
  '110,589',
  '+0.34%\n'],
 ['\xa0Aruba', 'Americas', 'Caribbean', '105,845', '106,314', '+0.44%\n'],
 ['\xa0U.S. Virgin Islands',
  'Americas',
  'Caribbean',
  '104,680',
  '104,578',
  '−0.10%\n'],
 ['\xa0Seychelles',
  'Africa',
  'Eastern Africa',
  '97,096',
  '97,739',
  '+0.66%\n'],
 ['\xa0Antigua and Barbuda',
  'Americas',
  'Caribbean',
  '96,286',
  '97,118',
  '+0.86%\n'],
 ['\xa0Isle of Man',
  'Europe',
  'Northern Europe',
  '84,077',
  '84,584',
  '+0.60%\n'],
 ['\xa0Andorra', 'Europe', 'Southern Europe', '77,006', '77,142', '+0.18%\n'],
 ['\xa0Dominica', 'Americas', 'Caribbean', '71,625', '71,808', '+0.26%\n'],
 ['\xa0Cayman Islands',
  'Americas',
  'Caribbean',
  '64,174',
  '64,948',
  '+1.21%\n'],
 ['\xa0Bermuda',
  'Americas',
  'Northern America',
  '62,756',
  '62,506',
  '−0.40%\n'],
 ['\xa0Marshall Islands',
  'Oceania',
  'Micronesia',
  '58,413',
  '58,791',
  '+0.65%\n'],
 ['\xa0Greenland',
  'Americas',
  'Northern America',
  '56,564',
  '56,672',
  '+0.19%\n'],
 ['\xa0Northern Mariana Islands',
  'Oceania',
  'Micronesia',
  '56,882',
  '56,188',
  '−1.22%\n'],
 ['\xa0American Samoa',
  'Oceania',
  'Polynesia',
  '55,465',
  '55,312',
  '−0.28%\n'],
 ['\xa0Saint Kitts and Nevis',
  'Americas',
  'Caribbean',
  '52,441',
  '52,823',
  '+0.73%\n'],
 ['\xa0Faroe Islands',
  'Europe',
  'Northern Europe',
  '48,497',
  '48,678',
  '+0.37%\n'],
 ['\xa0Sint Maarten', 'Americas', 'Caribbean', '41,940', '42,388', '+1.07%\n'],

In [10]:
len(headers + master_list)

240

In [12]:
[headers] + master_list

[['Country or area\n',
  'UN continentalregion[4]\n',
  'UN statisticalregion[4]\n',
  'Population(1 July 2018)\n',
  'Population(1 July 2019)\n',
  'Change\n'],
 ['\xa0China[a]',
  'Asia',
  'Eastern Asia',
  '1,427,647,786',
  '1,433,783,686',
  '+0.43%\n'],
 ['\xa0India',
  'Asia',
  'Southern Asia',
  '1,352,642,280',
  '1,366,417,754',
  '+1.02%\n'],
 ['\xa0United States',
  'Americas',
  'Northern America',
  '327,096,265',
  '329,064,917',
  '+0.60%\n'],
 ['\xa0Indonesia',
  'Asia',
  'South-eastern Asia',
  '267,670,543',
  '270,625,568',
  '+1.10%\n'],
 ['\xa0Pakistan',
  'Asia',
  'Southern Asia',
  '212,228,286',
  '216,565,318',
  '+2.04%\n'],
 ['\xa0Brazil',
  'Americas',
  'South America',
  '209,469,323',
  '211,049,527',
  '+0.75%\n'],
 ['\xa0Nigeria',
  'Africa',
  'Western Africa',
  '195,874,683',
  '200,963,599',
  '+2.60%\n'],
 ['\xa0Bangladesh',
  'Asia',
  'Southern Asia',
  '161,376,708',
  '163,046,161',
  '+1.03%\n'],
 ['\xa0Russia',
  'Europe',
  'Eastern Europe',
  '145,734,038',
  '145,872,256',
  '+0.09%\n'],
 ['\xa0Mexico',
  'Americas',
  'Central America',
  '126,190,788',
  '127,575,529',
  '+1.10%\n'],
 ['\xa0Japan',
  'Asia',
  'Eastern Asia',
  '127,202,192',
  '126,860,301',
  '−0.27%\n'],
 ['\xa0Ethiopia',
  'Africa',
  'Eastern Africa',
  '109,224,414',
  '112,078,730',
  '+2.61%\n'],
 ['\xa0Philippines',
  'Asia',
  'South-eastern Asia',
  '106,651,394',
  '108,116,615',
  '+1.37%\n'],
 ['\xa0Egypt',
  'Africa',
  'Northern Africa',
  '98,423,598',
  '100,388,073',
  '+2.00%\n'],
 ['\xa0Vietnam',
  'Asia',
  'South-eastern Asia',
  '95,545,962',
  '96,462,106',
  '+0.96%\n'],
 ['\xa0DR Congo',
  'Africa',
  'Middle Africa',
  '84,068,091',
  '86,790,567',
  '+3.24%\n'],
 ['\xa0Germany',
  'Europe',
  'Western Europe',
  '83,124,418',
  '83,517,045',
  '+0.47%\n'],
 ['\xa0Turkey',
  'Asia',
  'Western Asia',
  '82,340,088',
  '83,429,615',
  '+1.32%\n'],
 ['\xa0Iran', 'Asia', 'Southern Asia', '81,800,188', '82,913,906', '+1.36%\n'],
 ['\xa0Thailand',
  'Asia',
  'South-eastern Asia',
  '68,863,514',
  '69,037,513',
  '+0.25%\n'],
 ['\xa0United Kingdom',
  'Europe',
  'Northern Europe',
  '67,141,684',
  '67,530,172',
  '+0.58%\n'],
 ['\xa0France[b]',
  'Europe',
  'Western Europe',
  '64,990,511',
  '65,129,728',
  '+0.21%\n'],
 ['\xa0Italy',
  'Europe',
  'Southern Europe',
  '60,627,291',
  '60,550,075',
  '−0.13%\n'],
 ['\xa0South Africa',
  'Africa',
  'Southern Africa',
  '57,792,518',
  '58,558,270',
  '+1.33%\n'],
 ['\xa0Tanzania[c]',
  'Africa',
  'Eastern Africa',
  '56,313,438',
  '58,005,463',
  '+3.00%\n'],
 ['\xa0Myanmar',
  'Asia',
  'South-eastern Asia',
  '53,708,320',
  '54,045,420',
  '+0.63%\n'],
 ['\xa0Kenya',
  'Africa',
  'Eastern Africa',
  '51,392,565',
  '52,573,973',
  '+2.30%\n'],
 ['\xa0South Korea',
  'Asia',
  'Eastern Asia',
  '51,171,706',
  '51,225,308',
  '+0.10%\n'],
 ['\xa0Colombia',
  'Americas',
  'South America',
  '49,661,048',
  '50,339,443',
  '+1.37%\n'],
 ['\xa0Spain[d]',
  'Europe',
  'Southern Europe',
  '46,692,858',
  '46,736,776',
  '+0.09%\n'],
 ['\xa0Argentina',
  'Americas',
  'South America',
  '44,361,150',
  '44,780,677',
  '+0.95%\n'],
 ['\xa0Uganda',
  'Africa',
  'Eastern Africa',
  '42,729,036',
  '44,269,594',
  '+3.61%\n'],
 ['\xa0Ukraine[e]',
  'Europe',
  'Eastern Europe',
  '44,246,156',
  '43,993,638',
  '−0.57%\n'],
 ['\xa0Algeria',
  'Africa',
  'Northern Africa',
  '42,228,408',
  '43,053,054',
  '+1.95%\n'],
 ['\xa0Sudan',
  'Africa',
  'Northern Africa',
  '41,801,533',
  '42,813,238',
  '+2.42%\n'],
 ['\xa0Iraq', 'Asia', 'Western Asia', '38,433,600', '39,309,783', '+2.28%\n'],
 ['\xa0Afghanistan',
  'Asia',
  'Southern Asia',
  '37,171,921',
  '38,041,754',
  '+2.34%\n'],
 ['\xa0Poland',
  'Europe',
  'Eastern Europe',
  '37,921,592',
  '37,887,768',
  '−0.09%\n'],
 ['\xa0Canada',
  'Americas',
  'Northern America',
  '37,074,562',
  '37,411,047',
  '+0.91%\n'],
 ['\xa0Morocco',
  'Africa',
  'Northern Africa',
  '36,029,093',
  '36,471,769',
  '+1.23%\n'],
 ['\xa0Saudi Arabia',
  'Asia',
  'Western Asia',
  '33,702,756',
  '34,268,528',
  '+1.68%\n'],
 ['\xa0Uzbekistan',
  'Asia',
  'Central Asia',
  '32,476,244',
  '32,981,716',
  '+1.56%\n'],
 ['\xa0Peru',
  'Americas',
  'South America',
  '31,989,260',
  '32,510,453',
  '+1.63%\n'],
 ['\xa0Malaysia[f]',
  'Asia',
  'South-eastern Asia',
  '31,528,033',
  '31,949,777',
  '+1.34%\n'],
 ['\xa0Angola',
  'Africa',
  'Middle Africa',
  '30,809,787',
  '31,825,295',
  '+3.30%\n'],
 ['\xa0Mozambique',
  'Africa',
  'Eastern Africa',
  '29,496,004',
  '30,366,036',
  '+2.95%\n'],
 ['\xa0Yemen', 'Asia', 'Western Asia', '28,498,683', '29,161,922', '+2.33%\n'],
 ['\xa0Ghana',
  'Africa',
  'Western Africa',
  '28,206,728',
  '28,833,629',
  '+2.22%\n'],
 ['\xa0\xa0\xa0Nepal',
  'Asia',
  'Southern Asia',
  '28,095,714',
  '28,608,710',
  '+1.83%\n'],
 ['\xa0Venezuela',
  'Americas',
  'South America',
  '28,887,118',
  '28,515,829',
  '−1.29%\n'],
 ['\xa0Madagascar',
  'Africa',
  'Eastern Africa',
  '26,262,313',
  '26,969,307',
  '+2.69%\n'],
 ['\xa0North Korea',
  'Asia',
  'Eastern Asia',
  '25,549,604',
  '25,666,161',
  '+0.46%\n'],
 ['\xa0Ivory Coast',
  'Africa',
  'Western Africa',
  '25,069,230',
  '25,716,544',
  '+2.58%\n'],
 ['\xa0Cameroon',
  'Africa',
  'Middle Africa',
  '25,216,267',
  '25,876,380',
  '+2.62%\n'],
 ['\xa0Australia[g]',
  'Oceania',
  'Australia and New Zealand',
  '24,898,152',
  '25,203,198',
  '+1.23%\n'],
 ['\xa0Taiwan[h]',
  'Asia',
  'Eastern Asia',
  '23,726,460',
  '23,773,876',
  '+0.20%\n'],
 ['\xa0Niger',
  'Africa',
  'Western Africa',
  '22,442,822',
  '23,310,715',
  '+3.87%\n'],
 ['\xa0Sri Lanka',
  'Asia',
  'Southern Asia',
  '21,228,763',
  '21,323,733',
  '+0.45%\n'],
 ['\xa0Burkina Faso',
  'Africa',
  'Western Africa',
  '19,751,466',
  '20,321,378',
  '+2.89%\n'],
 ['\xa0Mali',
  'Africa',
  'Western Africa',
  '19,077,749',
  '19,658,031',
  '+3.04%\n'],
 ['\xa0Romania',
  'Europe',
  'Eastern Europe',
  '19,506,114',
  '19,364,557',
  '−0.73%\n'],
 ['\xa0Malawi',
  'Africa',
  'Eastern Africa',
  '18,143,217',
  '18,628,747',
  '+2.68%\n'],
 ['\xa0Chile',
  'Americas',
  'South America',
  '18,729,160',
  '18,952,038',
  '+1.19%\n'],
 ['\xa0Kazakhstan',
  'Asia',
  'Central Asia',
  '18,319,618',
  '18,551,427',
  '+1.27%\n'],
 ['\xa0Zambia',
  'Africa',
  'Eastern Africa',
  '17,351,708',
  '17,861,030',
  '+2.94%\n'],
 ['\xa0Guatemala',
  'Americas',
  'Central America',
  '17,247,849',
  '17,581,472',
  '+1.93%\n'],
 ['\xa0Ecuador',
  'Americas',
  'South America',
  '17,084,358',
  '17,373,662',
  '+1.69%\n'],
 ['\xa0Netherlands',
  'Europe',
  'Western Europe',
  '17,059,560',
  '17,097,130',
  '+0.22%\n'],
 ['\xa0Syria', 'Asia', 'Western Asia', '16,945,057', '17,070,135', '+0.74%\n'],
 ['\xa0Cambodia',
  'Asia',
  'South-eastern Asia',
  '16,249,792',
  '16,486,542',
  '+1.46%\n'],
 ['\xa0Senegal',
  'Africa',
  'Western Africa',
  '15,854,323',
  '16,296,364',
  '+2.79%\n'],
 ['\xa0Chad',
  'Africa',
  'Middle Africa',
  '15,477,729',
  '15,946,876',
  '+3.03%\n'],
 ['\xa0Somalia',
  'Africa',
  'Eastern Africa',
  '15,008,226',
  '15,442,905',
  '+2.90%\n'],
 ['\xa0Zimbabwe',
  'Africa',
  'Eastern Africa',
  '14,438,802',
  '14,645,468',
  '+1.43%\n'],
 ['\xa0Guinea',
  'Africa',
  'Western Africa',
  '12,414,293',
  '12,771,246',
  '+2.88%\n'],
 ['\xa0Rwanda',
  'Africa',
  'Eastern Africa',
  '12,301,970',
  '12,626,950',
  '+2.64%\n'],
 ['\xa0Benin',
  'Africa',
  'Western Africa',
  '11,485,044',
  '11,801,151',
  '+2.75%\n'],
 ['\xa0Tunisia',
  'Africa',
  'Northern Africa',
  '11,565,201',
  '11,694,719',
  '+1.12%\n'],
 ['\xa0Belgium',
  'Europe',
  'Western Europe',
  '11,482,178',
  '11,539,328',
  '+0.50%\n'],
 ['\xa0Bolivia',
  'Americas',
  'South America',
  '11,353,142',
  '11,513,100',
  '+1.41%\n'],
 ['\xa0Cuba', 'Americas', 'Caribbean', '11,338,134', '11,333,483', '−0.04%\n'],
 ['\xa0Haiti',
  'Americas',
  'Caribbean',
  '11,123,178',
  '11,263,770',
  '+1.26%\n'],
 ['\xa0South Sudan',
  'Africa',
  'Eastern Africa',
  '10,975,927',
  '11,062,113',
  '+0.79%\n'],
 ['\xa0Burundi',
  'Africa',
  'Eastern Africa',
  '10,524,117',
  '10,864,245',
  '+3.23%\n'],
 ['\xa0Dominican Republic',
  'Americas',
  'Caribbean',
  '10,627,141',
  '10,738,958',
  '+1.05%\n'],
 ['\xa0Czech Republic',
  'Europe',
  'Eastern Europe',
  '10,665,677',
  '10,689,209',
  '+0.22%\n'],
 ['\xa0Greece',
  'Europe',
  'Southern Europe',
  '10,522,246',
  '10,473,455',
  '−0.46%\n'],
 ['\xa0Portugal',
  'Europe',
  'Southern Europe',
  '10,256,193',
  '10,226,187',
  '−0.29%\n'],
 ['\xa0Jordan', 'Asia', 'Western Asia', '9,965,318', '10,101,694', '+1.37%\n'],
 ['\xa0Azerbaijan[i]',
  'Asia',
  'Western Asia',
  '9,949,537',
  '10,047,718',
  '+0.99%\n'],
 ['\xa0Sweden',
  'Europe',
  'Northern Europe',
  '9,971,638',
  '10,036,379',
  '+0.65%\n'],
 ['\xa0United Arab Emirates',
  'Asia',
  'Western Asia',
  '9,630,959',
  '9,770,529',
  '+1.45%\n'],
 ['\xa0Honduras',
  'Americas',
  'Central America',
  '9,587,522',
  '9,746,117',
  '+1.65%\n'],
 ['\xa0Hungary',
  'Europe',
  'Eastern Europe',
  '9,707,499',
  '9,684,679',
  '−0.24%\n'],
 ['\xa0Belarus',
  'Europe',
  'Eastern Europe',
  '9,452,617',
  '9,452,411',
  '0.00%\n'],
 ['\xa0Tajikistan',
  'Asia',
  'Central Asia',
  '9,100,835',
  '9,321,018',
  '+2.42%\n'],
 ['\xa0Austria',
  'Europe',
  'Western Europe',
  '8,891,388',
  '8,955,102',
  '+0.72%\n'],
 ['\xa0Papua New Guinea',
  'Oceania',
  'Melanesia',
  '8,606,323',
  '8,776,109',
  '+1.97%\n'],
 ['\xa0Serbia[j]',
  'Europe',
  'Southern Europe',
  '8,802,754',
  '8,772,235',
  '−0.35%\n'],
 ['\xa0\xa0Switzerland',
  'Europe',
  'Western Europe',
  '8,525,611',
  '8,591,365',
  '+0.77%\n'],
 ['\xa0Israel', 'Asia', 'Western Asia', '8,381,516', '8,519,377', '+1.64%\n'],
 ['\xa0Togo',
  'Africa',
  'Western Africa',
  '7,889,093',
  '8,082,366',
  '+2.45%\n'],
 ['\xa0Sierra Leone',
  'Africa',
  'Western Africa',
  '7,650,150',
  '7,813,215',
  '+2.13%\n'],
 ['\xa0Hong Kong',
  'Asia',
  'Eastern Asia',
  '7,371,730',
  '7,436,154',
  '+0.87%\n'],
 ['\xa0Laos',
  'Asia',
  'South-eastern Asia',
  '7,061,507',
  '7,169,455',
  '+1.53%\n'],
 ['\xa0Paraguay',
  'Americas',
  'South America',
  '6,956,066',
  '7,044,636',
  '+1.27%\n'],
 ['\xa0Bulgaria',
  'Europe',
  'Eastern Europe',
  '7,051,608',
  '7,000,119',
  '−0.73%\n'],
 ['\xa0Lebanon', 'Asia', 'Western Asia', '6,859,408', '6,855,713', '−0.05%\n'],
 ['\xa0Libya',
  'Africa',
  'Northern Africa',
  '6,678,559',
  '6,777,452',
  '+1.48%\n'],
 ['\xa0Nicaragua',
  'Americas',
  'Central America',
  '6,465,501',
  '6,545,502',
  '+1.24%\n'],
 ['\xa0El Salvador',
  'Americas',
  'Central America',
  '6,420,746',
  '6,453,553',
  '+0.51%\n'],
 ['\xa0Kyrgyzstan',
  'Asia',
  'Central Asia',
  '6,304,030',
  '6,415,850',
  '+1.77%\n'],
 ['\xa0Turkmenistan',
  'Asia',
  'Central Asia',
  '5,850,901',
  '5,942,089',
  '+1.56%\n'],
 ['\xa0Singapore',
  'Asia',
  'South-eastern Asia',
  '5,757,499',
  '5,804,337',
  '+0.81%\n'],
 ['\xa0Denmark',
  'Europe',
  'Northern Europe',
  '5,752,126',
  '5,771,876',
  '+0.34%\n'],
 ['\xa0Finland[k]',
  'Europe',
  'Northern Europe',
  '5,522,576',
  '5,532,156',
  '+0.17%\n'],
 ['\xa0Slovakia',
  'Europe',
  'Eastern Europe',
  '5,453,014',
  '5,457,013',
  '+0.07%\n'],
 ['\xa0Congo',
  'Africa',
  'Middle Africa',
  '5,244,359',
  '5,380,508',
  '+2.60%\n'],
 ['\xa0Norway[l]',
  'Europe',
  'Northern Europe',
  '5,337,962',
  '5,378,857',
  '+0.77%\n'],
 ['\xa0Costa Rica',
  'Americas',
  'Central America',
  '4,999,441',
  '5,047,561',
  '+0.96%\n'],
 ['\xa0Palestine[m]',
  'Asia',
  'Western Asia',
  '4,862,979',
  '4,981,420',
  '+2.44%\n'],
 ['\xa0Oman', 'Asia', 'Western Asia', '4,829,473', '4,974,986', '+3.01%\n'],
 ['\xa0Liberia',
  'Africa',
  'Western Africa',
  '4,818,973',
  '4,937,374',
  '+2.46%\n'],
 ['\xa0Ireland',
  'Europe',
  'Northern Europe',
  '4,818,690',
  '4,882,495',
  '+1.32%\n'],
 ['\xa0New Zealand',
  'Oceania',
  'Australia and New Zealand',
  '4,743,131',
  '4,783,063',
  '+0.84%\n'],
 ['\xa0Central African Republic',
  'Africa',
  'Middle Africa',
  '4,666,368',
  '4,745,185',
  '+1.69%\n'],
 ['\xa0Mauritania',
  'Africa',
  'Western Africa',
  '4,403,313',
  '4,525,696',
  '+2.78%\n'],
 ['\xa0Panama',
  'Americas',
  'Central America',
  '4,176,869',
  '4,246,439',
  '+1.67%\n'],
 ['\xa0Kuwait', 'Asia', 'Western Asia', '4,137,312', '4,207,083', '+1.69%\n'],
 ['\xa0Croatia',
  'Europe',
  'Southern Europe',
  '4,156,405',
  '4,130,304',
  '−0.63%\n'],
 ['\xa0Moldova[n]',
  'Europe',
  'Eastern Europe',
  '4,051,944',
  '4,043,263',
  '−0.21%\n'],
 ['\xa0Georgia[o]',
  'Asia',
  'Western Asia',
  '4,002,942',
  '3,996,765',
  '−0.15%\n'],
 ['\xa0Eritrea',
  'Africa',
  'Eastern Africa',
  '3,452,786',
  '3,497,117',
  '+1.28%\n'],
 ['\xa0Uruguay',
  'Americas',
  'South America',
  '3,449,285',
  '3,461,734',
  '+0.36%\n'],
 ['\xa0Bosnia and Herzegovina',
  'Europe',
  'Southern Europe',
  '3,323,925',
  '3,301,000',
  '−0.69%\n'],
 ['\xa0Mongolia',
  'Asia',
  'Eastern Asia',
  '3,170,216',
  '3,225,167',
  '+1.73%\n'],
 ['\xa0Armenia', 'Asia', 'Western Asia', '2,951,745', '2,957,731', '+0.20%\n'],
 ['\xa0Jamaica',
  'Americas',
  'Caribbean',
  '2,934,847',
  '2,948,279',
  '+0.46%\n'],
 ['\xa0Puerto Rico',
  'Americas',
  'Caribbean',
  '3,039,596',
  '2,933,408',
  '−3.49%\n'],
 ['\xa0Albania',
  'Europe',
  'Southern Europe',
  '2,882,740',
  '2,880,917',
  '−0.06%\n'],
 ['\xa0Qatar', 'Asia', 'Western Asia', '2,781,682', '2,832,067', '+1.81%\n'],
 ['\xa0Lithuania',
  'Europe',
  'Northern Europe',
  '2,801,264',
  '2,759,627',
  '−1.49%\n'],
 ['\xa0Namibia',
  'Africa',
  'Southern Africa',
  '2,448,301',
  '2,494,530',
  '+1.89%\n'],
 ['\xa0Gambia',
  'Africa',
  'Western Africa',
  '2,280,094',
  '2,347,706',
  '+2.97%\n'],
 ['\xa0Botswana',
  'Africa',
  'Southern Africa',
  '2,254,068',
  '2,303,697',
  '+2.20%\n'],
 ['\xa0Gabon',
  'Africa',
  'Middle Africa',
  '2,119,275',
  '2,172,579',
  '+2.52%\n'],
 ['\xa0Lesotho',
  'Africa',
  'Southern Africa',
  '2,108,328',
  '2,125,268',
  '+0.80%\n'],
 ['\xa0North Macedonia',
  'Europe',
  'Southern Europe',
  '2,082,957',
  '2,083,459',
  '+0.02%\n'],
 ['\xa0Slovenia',
  'Europe',
  'Southern Europe',
  '2,077,837',
  '2,078,654',
  '+0.04%\n'],
 ['\xa0Guinea-Bissau',
  'Africa',
  'Western Africa',
  '1,874,303',
  '1,920,922',
  '+2.49%\n'],
 ['\xa0Latvia',
  'Europe',
  'Northern Europe',
  '1,928,459',
  '1,906,743',
  '−1.13%\n'],
 ['\xa0Bahrain', 'Asia', 'Western Asia', '1,569,446', '1,641,172', '+4.57%\n'],
 ['\xa0Trinidad and Tobago',
  'Americas',
  'Caribbean',
  '1,389,843',
  '1,394,973',
  '+0.37%\n'],
 ['\xa0Equatorial Guinea',
  'Africa',
  'Middle Africa',
  '1,308,975',
  '1,355,986',
  '+3.59%\n'],
 ['\xa0Estonia',
  'Europe',
  'Northern Europe',
  '1,322,920',
  '1,325,648',
  '+0.21%\n'],
 ['\xa0East Timor',
  'Asia',
  'South-eastern Asia',
  '1,267,974',
  '1,293,119',
  '+1.98%\n'],
 ['\xa0Mauritius[p]',
  'Africa',
  'Eastern Africa',
  '1,189,265',
  '1,198,575',
  '+0.78%\n'],
 ['\xa0Cyprus[q]',
  'Asia',
  'Western Asia',
  '1,170,125',
  '1,179,551',
  '+0.81%\n'],
 ['\xa0Eswatini',
  'Africa',
  'Southern Africa',
  '1,136,281',
  '1,148,130',
  '+1.04%\n'],
 ['\xa0Djibouti',
  'Africa',
  'Eastern Africa',
  '958,923',
  '973,560',
  '+1.53%\n'],
 ['\xa0Fiji', 'Oceania', 'Melanesia', '883,483', '889,953', '+0.73%\n'],
 ['\xa0Réunion', 'Africa', 'Eastern Africa', '882,526', '888,927', '+0.73%\n'],
 ['\xa0Comoros', 'Africa', 'Eastern Africa', '832,322', '850,886', '+2.23%\n'],
 ['\xa0Guyana', 'Americas', 'South America', '779,006', '782,766', '+0.48%\n'],
 ['\xa0Bhutan', 'Asia', 'Southern Asia', '754,388', '763,092', '+1.15%\n'],
 ['\xa0Solomon Islands',
  'Oceania',
  'Melanesia',
  '652,857',
  '669,823',
  '+2.60%\n'],
 ['\xa0Macau', 'Asia', 'Eastern Asia', '631,636', '640,445', '+1.39%\n'],
 ['\xa0Montenegro',
  'Europe',
  'Southern Europe',
  '627,809',
  '627,987',
  '+0.03%\n'],
 ['\xa0Luxembourg',
  'Europe',
  'Western Europe',
  '604,245',
  '615,729',
  '+1.90%\n'],
 ['\xa0Western Sahara',
  'Africa',
  'Northern Africa',
  '567,402',
  '582,463',
  '+2.65%\n'],
 ['\xa0Suriname',
  'Americas',
  'South America',
  '575,990',
  '581,372',
  '+0.93%\n'],
 ['\xa0Cape Verde',
  'Africa',
  'Western Africa',
  '543,767',
  '549,935',
  '+1.13%\n'],
 ['\xa0Maldives', 'Asia', 'Southern Asia', '515,696', '530,953', '+2.96%\n'],
 ['\xa0Guadeloupe[r]',
  'Americas',
  'Caribbean',
  '446,928',
  '447,905',
  '+0.22%\n'],
 ['\xa0Malta', 'Europe', 'Southern Europe', '439,248', '440,372', '+0.26%\n'],
 ['\xa0Brunei',
  'Asia',
  'South-eastern Asia',
  '428,963',
  '433,285',
  '+1.01%\n'],
 ['\xa0Belize',
  'Americas',
  'Central America',
  '383,071',
  '390,353',
  '+1.90%\n'],
 ['\xa0Bahamas', 'Americas', 'Caribbean', '385,637', '389,482', '+1.00%\n'],
 ['\xa0Martinique', 'Americas', 'Caribbean', '375,673', '375,554', '−0.03%\n'],
 ['\xa0Iceland',
  'Europe',
  'Northern Europe',
  '336,713',
  '339,031',
  '+0.69%\n'],
 ['\xa0Vanuatu', 'Oceania', 'Melanesia', '292,680', '299,882', '+2.46%\n'],
 ['\xa0Barbados', 'Americas', 'Caribbean', '286,641', '287,025', '+0.13%\n'],
 ['\xa0New Caledonia',
  'Oceania',
  'Melanesia',
  '279,993',
  '282,750',
  '+0.98%\n'],
 ['\xa0French Guiana',
  'Americas',
  'South America',
  '275,713',
  '282,731',
  '+2.55%\n'],
 ['\xa0French Polynesia',
  'Oceania',
  'Polynesia',
  '277,679',
  '279,287',
  '+0.58%\n'],
 ['\xa0Mayotte', 'Africa', 'Eastern Africa', '259,531', '266,150', '+2.55%\n'],
 ['\xa0São Tomé and Príncipe',
  'Africa',
  'Middle Africa',
  '211,028',
  '215,056',
  '+1.91%\n'],
 ['\xa0Samoa', 'Oceania', 'Polynesia', '196,129', '197,097', '+0.49%\n'],
 ['\xa0Saint Lucia',
  'Americas',
  'Caribbean',
  '181,889',
  '182,790',
  '+0.50%\n'],
 ['\xa0Guernsey and \xa0Jersey',
  'Europe',
  'Northern Europe',
  '170,499',
  '172,259',
  '+1.03%\n'],
 ['\xa0Guam', 'Oceania', 'Micronesia', '165,768', '167,294', '+0.92%\n'],
 ['\xa0Curaçao', 'Americas', 'Caribbean', '162,752', '163,424', '+0.41%\n'],
 ['\xa0Kiribati', 'Oceania', 'Micronesia', '115,847', '117,606', '+1.52%\n'],
 ['\xa0F.S. Micronesia',
  'Oceania',
  'Micronesia',
  '112,640',
  '113,815',
  '+1.04%\n'],
 ['\xa0Grenada', 'Americas', 'Caribbean', '111,454', '112,003', '+0.49%\n'],
 ['\xa0Tonga', 'Oceania', 'Polynesia', '110,589', '110,940', '+0.32%\n'],
 ['\xa0Saint Vincent and the Grenadines',
  'Americas',
  'Caribbean',
  '110,211',
  '110,589',
  '+0.34%\n'],
 ['\xa0Aruba', 'Americas', 'Caribbean', '105,845', '106,314', '+0.44%\n'],
 ['\xa0U.S. Virgin Islands',
  'Americas',
  'Caribbean',
  '104,680',
  '104,578',
  '−0.10%\n'],
 ['\xa0Seychelles',
  'Africa',
  'Eastern Africa',
  '97,096',
  '97,739',
  '+0.66%\n'],
 ['\xa0Antigua and Barbuda',
  'Americas',
  'Caribbean',
  '96,286',
  '97,118',
  '+0.86%\n'],
 ['\xa0Isle of Man',
  'Europe',
  'Northern Europe',
  '84,077',
  '84,584',
  '+0.60%\n'],
 ['\xa0Andorra', 'Europe', 'Southern Europe', '77,006', '77,142', '+0.18%\n'],
 ['\xa0Dominica', 'Americas', 'Caribbean', '71,625', '71,808', '+0.26%\n'],
 ['\xa0Cayman Islands',
  'Americas',
  'Caribbean',
  '64,174',
  '64,948',
  '+1.21%\n'],
 ['\xa0Bermuda',
  'Americas',
  'Northern America',
  '62,756',
  '62,506',
  '−0.40%\n'],
 ['\xa0Marshall Islands',
  'Oceania',
  'Micronesia',
  '58,413',
  '58,791',
  '+0.65%\n'],
 ['\xa0Greenland',
  'Americas',
  'Northern America',
  '56,564',
  '56,672',
  '+0.19%\n'],
 ['\xa0Northern Mariana Islands',
  'Oceania',
  'Micronesia',
  '56,882',
  '56,188',
  '−1.22%\n'],
 ['\xa0American Samoa',
  'Oceania',
  'Polynesia',
  '55,465',
  '55,312',
  '−0.28%\n'],
 ['\xa0Saint Kitts and Nevis',
  'Americas',
  'Caribbean',
  '52,441',
  '52,823',
  '+0.73%\n'],
 ['\xa0Faroe Islands',
  'Europe',
  'Northern Europe',
  '48,497',

In [13]:
len([headers] + master_list)

235

In [19]:
# aliasing 
import pandas as pd

In [ ]:
pd.DataFrame

In [17]:
import random
random.randint(0,1)

0

In [20]:
# pandas dataframe === Excel file

In [21]:
df = pd.DataFrame([headers] + master_list)

In [22]:
df

,0,1,2,3,4,5
0,Country or area\n,UN continentalregion[4]\n,UN statisticalregion[4]\n,Population(1 July 2018)\n,Population(1 July 2019)\n,Change\n
1,China[a],Asia,Eastern Asia,"1,427,647,786","1,433,783,686",+0.43%\n
2,India,Asia,Southern Asia,"1,352,642,280","1,366,417,754",+1.02%\n
3,United States,Americas,Northern America,"327,096,265","329,064,917",+0.60%\n
4,Indonesia,Asia,South-eastern Asia,"267,670,543","270,625,568",+1.10%\n
...,...,...,...,...,...,...
230,Falkland Islands,Americas,South America,"3,234","3,377",+4.42%\n
231,Niue,Oceania,Polynesia,"1,620","1,615",−0.31%\n
232,Tokelau,Oceania,Polynesia,"1,319","1,340",+1.59%\n
233,Vatican City[t],Europe,Southern Europe,801,799,−0.25%\n
234,None,None,None,None,None,None

In [24]:
df = pd.DataFrame(master_list, columns = headers)
df

,Country or area\n,UN continentalregion[4]\n,UN statisticalregion[4]\n,Population(1 July 2018)\n,Population(1 July 2019)\n,Change\n
0,China[a],Asia,Eastern Asia,"1,427,647,786","1,433,783,686",+0.43%\n
1,India,Asia,Southern Asia,"1,352,642,280","1,366,417,754",+1.02%\n
2,United States,Americas,Northern America,"327,096,265","329,064,917",+0.60%\n
3,Indonesia,Asia,South-eastern Asia,"267,670,543","270,625,568",+1.10%\n
4,Pakistan,Asia,Southern Asia,"212,228,286","216,565,318",+2.04%\n
...,...,...,...,...,...,...
229,Falkland Islands,Americas,South America,"3,234","3,377",+4.42%\n
230,Niue,Oceania,Polynesia,"1,620","1,615",−0.31%\n
231,Tokelau,Oceania,Polynesia,"1,319","1,340",+1.59%\n
232,Vatican City[t],Europe,Southern Europe,801,799,−0.25%\n
233,None,None,None,None,None,None

In [27]:
df.head()

,Country or area\n,UN continentalregion[4]\n,UN statisticalregion[4]\n,Population(1 July 2018)\n,Population(1 July 2019)\n,Change\n
0,China[a],Asia,Eastern Asia,"1,427,647,786","1,433,783,686",+0.43%\n
1,India,Asia,Southern Asia,"1,352,642,280","1,366,417,754",+1.02%\n
2,United States,Americas,Northern America,"327,096,265","329,064,917",+0.60%\n
3,Indonesia,Asia,South-eastern Asia,"267,670,543","270,625,568",+1.10%\n
4,Pakistan,Asia,Southern Asia,"212,228,286","216,565,318",+2.04%\n

In [28]:
df.tail()

,Country or area\n,UN continentalregion[4]\n,UN statisticalregion[4]\n,Population(1 July 2018)\n,Population(1 July 2019)\n,Change\n
229,Falkland Islands,Americas,South America,"3,234","3,377",+4.42%\n
230,Niue,Oceania,Polynesia,"1,620","1,615",−0.31%\n
231,Tokelau,Oceania,Polynesia,"1,319","1,340",+1.59%\n
232,Vatican City[t],Europe,Southern Europe,801,799,−0.25%\n
233,None,None,None,None,None,None

In [32]:
df.loc[:, 'myname'] = 'Mike'
df.loc[:, 'yourname'] = 'Joe'
df.loc[:, 'combinedname'] = df.myname + df.yourname
df.loc[:, 'country_continent'] = df['UN continentalregion[4]\n'] + df['myname']
df

,Country or area\n,UN continentalregion[4]\n,UN statisticalregion[4]\n,Population(1 July 2018)\n,Population(1 July 2019)\n,Change\n,myname,yourname,combinedname,country_continent
0,China[a],Asia,Eastern Asia,"1,427,647,786","1,433,783,686",+0.43%\n,Mike,Joe,MikeJoe,AsiaMike
1,India,Asia,Southern Asia,"1,352,642,280","1,366,417,754",+1.02%\n,Mike,Joe,MikeJoe,AsiaMike
2,United States,Americas,Northern America,"327,096,265","329,064,917",+0.60%\n,Mike,Joe,MikeJoe,AmericasMike
3,Indonesia,Asia,South-eastern Asia,"267,670,543","270,625,568",+1.10%\n,Mike,Joe,MikeJoe,AsiaMike
4,Pakistan,Asia,Southern Asia,"212,228,286","216,565,318",+2.04%\n,Mike,Joe,MikeJoe,AsiaMike
...,...,...,...,...,...,...,...,...,...,...
229,Falkland Islands,Americas,South America,"3,234","3,377",+4.42%\n,Mike,Joe,MikeJoe,AmericasMike
230,Niue,Oceania,Polynesia,"1,620","1,615",−0.31%\n,Mike,Joe,MikeJoe,OceaniaMike
231,Tokelau,Oceania,Polynesia,"1,319","1,340",+1.59%\n,Mike,Joe,MikeJoe,OceaniaMike
232,Vatican City[t],Europe,Southern Europe,801,799,−0.25%\n,Mike,Joe,MikeJoe,EuropeMike
233,None,None,None,None,None,None,Mike,Joe,MikeJoe,NaN

In [41]:
def add_population(row):
    total_population = row['Population(1 July 2018)\n'] + row['Population(1 July 2019)\n']
    return total_population

df.loc[:, 'total_pop'] = df.apply(add_population, axis = 1)
df

,Country or area\n,UN continentalregion[4]\n,UN statisticalregion[4]\n,Population(1 July 2018)\n,Population(1 July 2019)\n,Change\n,myname,yourname,combinedname,country_continent,total_pop
0,China[a],Asia,Eastern Asia,"1,427,647,786","1,433,783,686",+0.43%\n,Mike,Joe,MikeJoe,AsiaMike,"1,427,647,7861,433,783,686"
1,India,Asia,Southern Asia,"1,352,642,280","1,366,417,754",+1.02%\n,Mike,Joe,MikeJoe,AsiaMike,"1,352,642,2801,366,417,754"
2,United States,Americas,Northern America,"327,096,265","329,064,917",+0.60%\n,Mike,Joe,MikeJoe,AmericasMike,"327,096,265329,064,917"
3,Indonesia,Asia,South-eastern Asia,"267,670,543","270,625,568",+1.10%\n,Mike,Joe,MikeJoe,AsiaMike,"267,670,543270,625,568"
4,Pakistan,Asia,Southern Asia,"212,228,286","216,565,318",+2.04%\n,Mike,Joe,MikeJoe,AsiaMike,"212,228,286216,565,318"
...,...,...,...,...,...,...,...,...,...,...,...
228,Montserrat,Americas,Caribbean,"4,993","4,989",−0.08%\n,Mike,Joe,MikeJoe,AmericasMike,"4,9934,989"
229,Falkland Islands,Americas,South America,"3,234","3,377",+4.42%\n,Mike,Joe,MikeJoe,AmericasMike,"3,2343,377"
230,Niue,Oceania,Polynesia,"1,620","1,615",−0.31%\n,Mike,Joe,MikeJoe,OceaniaMike,"1,6201,615"
231,Tokelau,Oceania,Polynesia,"1,319","1,340",+1.59%\n,Mike,Joe,MikeJoe,OceaniaMike,"1,3191,340"
232,Vatican City[t],Europe,Southern Europe,801,799,−0.25%\n,Mike,Joe,MikeJoe,EuropeMike,801799

In [38]:
df = df[ df['Country or area\n'].notna() ]
df.tail()

,Country or area\n,UN continentalregion[4]\n,UN statisticalregion[4]\n,Population(1 July 2018)\n,Population(1 July 2019)\n,Change\n,myname,yourname,combinedname,country_continent
228,Montserrat,Americas,Caribbean,"4,993","4,989",−0.08%\n,Mike,Joe,MikeJoe,AmericasMike
229,Falkland Islands,Americas,South America,"3,234","3,377",+4.42%\n,Mike,Joe,MikeJoe,AmericasMike
230,Niue,Oceania,Polynesia,"1,620","1,615",−0.31%\n,Mike,Joe,MikeJoe,OceaniaMike
231,Tokelau,Oceania,Polynesia,"1,319","1,340",+1.59%\n,Mike,Joe,MikeJoe,OceaniaMike
232,Vatican City[t],Europe,Southern Europe,801,799,−0.25%\n,Mike,Joe,MikeJoe,EuropeMike

In [43]:
df.to_csv('/Users/mdavis/Desktop/test2.csv')

In [45]:
a = pd.read_csv('/Users/mdavis/Desktop/test2.csv')
a

,Unnamed: 0,Country or area\n,UN continentalregion[4]\n,UN statisticalregion[4]\n,Population(1 July 2018)\n,Population(1 July 2019)\n,Change\n,myname,yourname,combinedname,country_continent,total_pop
0,0,China[a],Asia,Eastern Asia,"1,427,647,786","1,433,783,686",+0.43%\n,Mike,Joe,MikeJoe,AsiaMike,"1,427,647,7861,433,783,686"
1,1,India,Asia,Southern Asia,"1,352,642,280","1,366,417,754",+1.02%\n,Mike,Joe,MikeJoe,AsiaMike,"1,352,642,2801,366,417,754"
2,2,United States,Americas,Northern America,"327,096,265","329,064,917",+0.60%\n,Mike,Joe,MikeJoe,AmericasMike,"327,096,265329,064,917"
3,3,Indonesia,Asia,South-eastern Asia,"267,670,543","270,625,568",+1.10%\n,Mike,Joe,MikeJoe,AsiaMike,"267,670,543270,625,568"
4,4,Pakistan,Asia,Southern Asia,"212,228,286","216,565,318",+2.04%\n,Mike,Joe,MikeJoe,AsiaMike,"212,228,286216,565,318"
...,...,...,...,...,...,...,...,...,...,...,...,...
228,228,Montserrat,Americas,Caribbean,"4,993","4,989",−0.08%\n,Mike,Joe,MikeJoe,AmericasMike,"4,9934,989"
229,229,Falkland Islands,Americas,South America,"3,234","3,377",+4.42%\n,Mike,Joe,MikeJoe,AmericasMike,"3,2343,377"
230,230,Niue,Oceania,Polynesia,"1,620","1,615",−0.31%\n,Mike,Joe,MikeJoe,OceaniaMike,"1,6201,615"
231,231,Tokelau,Oceania,Polynesia,"1,319","1,340",+1.59%\n,Mike,Joe,MikeJoe,OceaniaMike,"1,3191,340"
232,232,Vatican City[t],Europe,Southern Europe,801,799,−0.25%\n,Mike,Joe,MikeJoe,EuropeMike,801799

In [47]:
df[['myname','yourname']].myname.unique()

array(['Mike'], dtype=object)